name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10, 12, 14]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - name: Dump GitHub context
      id: github_context_step
      run: echo '${{ toJSON(github) }}'
    - name: Dump job context
      run: echo '${{ toJSON(job) }}'
    - name: Dump matrix context
      run: echo '${{ toJSON(matrix) }}'
    - name: Dump env context
      run: echo '${{ toJSON(env) }}'
    - name: Dump env context
      run: echo '${{ toJSON(runner) }}'
    - name: Dump needs context
      run: echo '${{ toJSON(needs) }}'
    - name: Dump needs context
      run: echo '${{ toJSON(inputs) }}'
