name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10, 12, 14]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - name: Dump GitHub context
      id: github_context_step
      run: echo '${{ toJSON(github) }}'
    - name: Dump job context
      run: echo '${{ toJSON(job) }}'
    - name: Dump matrix context
      run: echo '${{ toJSON(matrix) }}'
    - name: Dump env context
      run: echo '${{ toJSON(env) }}'
    - name: Dump runner context
      run: echo '${{ toJSON(runner) }}'
    - name: Dump needs context
      run: echo '${{ toJSON(needs) }}'
    - name: Dump inputs context
      run: echo '${{ toJSON(inputs) }}'
    - name: url
      run: echo ${{ steps.step_name.outputs.url_output }}
    - name: get the check run id for each job
      run: |
        CHECK_SUITE_URL=$(curl -s -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID} | jq -r '.check_suite_url')
        CHECK_RUN_ID=$(curl -s -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.antiope-preview+json" $CHECK_SUITE_URL/check-runs | jq '.check_runs[] | select(.name=="prcheck (${{ matrix.os }})") | .id ')
        echo $CHECK_RUN_ID
